set(GARNET_MRUBY_SOURCE_DIR "" CACHE PATH "Optional local pinned mruby checkout; empty fetches upstream source")
set(GARNET_MRUBY_BUILD_DIR "" CACHE PATH "Advanced: completed Garnet-managed mruby build with manifest")
set(_garnet_revision 831da26b9021de0369d17b71b5667e2941a1a32d) # mruby 4.0.0
if(GARNET_MRUBY_SOURCE_DIR AND GARNET_MRUBY_BUILD_DIR)
  message(FATAL_ERROR "Choose either GARNET_MRUBY_SOURCE_DIR or GARNET_MRUBY_BUILD_DIR")
endif()
if(CMAKE_CROSSCOMPILING)
  message(FATAL_ERROR "Garnet mruby currently requires a native build: mrbc must execute on the build host")
endif()
if(CMAKE_CONFIGURATION_TYPES)
  set(_configs ${CMAKE_CONFIGURATION_TYPES})
elseif(CMAKE_BUILD_TYPE)
  set(_configs ${CMAKE_BUILD_TYPE})
else()
  message(FATAL_ERROR "Set CMAKE_BUILD_TYPE, for example Release or Debug")
endif()
if(NOT CMAKE_C_COMPILER_ID STREQUAL CMAKE_CXX_COMPILER_ID)
  message(FATAL_ERROR "Use the same C/C++ compiler family for Garnet and mruby")
endif()
if(GARNET_MRUBY_BUILD_DIR AND CMAKE_CONFIGURATION_TYPES)
  message(FATAL_ERROR "Prebuilt mruby currently requires a single-configuration generator")
endif()
if(NOT GARNET_MRUBY_SOURCE_DIR AND NOT GARNET_MRUBY_BUILD_DIR)
  include(FetchContent)
  FetchContent_Declare(garnet_mruby_source
    GIT_REPOSITORY https://github.com/mruby/mruby.git
    GIT_TAG ${_garnet_revision}
    GIT_SUBMODULES "")
  # mruby is built by minirake below, not by add_subdirectory.
  FetchContent_MakeAvailable(garnet_mruby_source)
  set(GARNET_MRUBY_SOURCE_DIR "${garnet_mruby_source_SOURCE_DIR}")
endif()
file(SHA256 "${CMAKE_CURRENT_LIST_DIR}/mruby_build_config.rb" _recipe_hash)
file(SHA256 "${CMAKE_CURRENT_LIST_FILE}" _driver_hash)
set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS
  "${CMAKE_CURRENT_LIST_DIR}/mruby_build_config.rb")
set(_inputs_hash "")
if(GARNET_MRUBY_SOURCE_DIR)
  if(NOT EXISTS "${GARNET_MRUBY_SOURCE_DIR}/minirake")
    message(FATAL_ERROR "Supply GARNET_MRUBY_SOURCE_DIR pointing to the pinned local mruby checkout")
  endif()
  find_package(Git REQUIRED)
  execute_process(COMMAND "${GIT_EXECUTABLE}" -C "${GARNET_MRUBY_SOURCE_DIR}" rev-parse HEAD
    OUTPUT_VARIABLE _revision OUTPUT_STRIP_TRAILING_WHITESPACE RESULT_VARIABLE _git_result)
  if(NOT _git_result EQUAL 0 OR NOT _revision STREQUAL _garnet_revision)
    message(FATAL_ERROR "mruby source must be checked out at ${_garnet_revision}")
  endif()
  # mruby's MSVC toolchain does not emit header dependency files. Conservatively
  # rebuild all of mruby when a tracked input changes, including symbol inputs.
  execute_process(COMMAND "${GIT_EXECUTABLE}" -C "${GARNET_MRUBY_SOURCE_DIR}" ls-files
    OUTPUT_VARIABLE _tracked OUTPUT_STRIP_TRAILING_WHITESPACE COMMAND_ERROR_IS_FATAL ANY)
  string(REPLACE "\n" ";" _tracked "${_tracked}")
  foreach(_input IN LISTS _tracked)
    set(_input "${GARNET_MRUBY_SOURCE_DIR}/${_input}")
    file(SHA256 "${_input}" _hash)
    string(APPEND _inputs_hash "${_hash}")
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${_input}")
  endforeach()
  string(SHA256 _inputs_hash "${_inputs_hash}")
endif()
function(_garnet_json_set var key value)
  string(REPLACE "\\" "\\\\" value "${value}")
  string(REPLACE "\"" "\\\"" value "${value}")
  string(REPLACE "\n" "\\n" value "${value}")
  string(REPLACE "\r" "\\r" value "${value}")
  string(REPLACE "\t" "\\t" value "${value}")
  string(JSON json SET "${${var}}" "${key}" "\"${value}\"")
  set(${var} "${json}" PARENT_SCOPE)
endfunction()
add_library(garnet_mruby INTERFACE)
target_compile_definitions(garnet_mruby INTERFACE MRB_USE_CXX_EXCEPTION MRB_INT64 MRB_WORDBOX_NO_INLINE_FLOAT MRB_USE_BIGINT)
if(CMAKE_SIZEOF_VOID_P EQUAL 4)
  # mruby 4 requires unboxed values for 64-bit integers on 32-bit hosts.
  target_compile_definitions(garnet_mruby INTERFACE MRB_NO_BOXING)
endif()
foreach(_config IN LISTS _configs)
  string(TOUPPER "${_config}" _upper)
  set(_cflags "${CMAKE_C_FLAGS} ${CMAKE_C_FLAGS_${_upper}}")
  set(_cxxflags "${CMAKE_CXX_FLAGS} ${CMAKE_CXX_FLAGS_${_upper}}")
  set(_ldflags "${CMAKE_EXE_LINKER_FLAGS} ${CMAKE_EXE_LINKER_FLAGS_${_upper}}")
  if(MSVC)
    set(_crt "${CMAKE_MSVC_RUNTIME_LIBRARY}")
    if(NOT _crt)
      set(_crt "MultiThreaded$<$<CONFIG:Debug>:Debug>DLL")
    endif()
    if(_upper STREQUAL "DEBUG")
      string(REPLACE "$<$<CONFIG:Debug>:Debug>" Debug _crt "${_crt}")
    else()
      string(REPLACE "$<$<CONFIG:Debug>:Debug>" "" _crt "${_crt}")
    endif()
    if(_crt STREQUAL "MultiThreadedDLL")
      set(_crt_flag /MD)
    elseif(_crt STREQUAL "MultiThreadedDebugDLL")
      set(_crt_flag /MDd)
    elseif(_crt STREQUAL "MultiThreaded")
      set(_crt_flag /MT)
    elseif(_crt STREQUAL "MultiThreadedDebug")
      set(_crt_flag /MTd)
    else()
      message(FATAL_ERROR "Unsupported MSVC runtime expression: ${_crt}")
    endif()
    string(APPEND _cflags " ${_crt_flag} /D_CRT_SECURE_NO_WARNINGS")
    # mruby 4's C++ exception wrappers use designated initializers.
    string(APPEND _cxxflags " ${_crt_flag} /D_CRT_SECURE_NO_WARNINGS /EHs /EHc- /std:c++20 /utf-8")
    string(APPEND _cflags " /EHs /EHc- /utf-8")
    set(_ld "${CMAKE_LINKER}")
    set(_libname libmruby.lib)
    set(_msvc true)
  else()
    string(APPEND _cflags " -fPIC")
    string(APPEND _cxxflags " -fPIC -std=c++20")
    if(CMAKE_SYSROOT)
      string(APPEND _cflags " --sysroot=\"${CMAKE_SYSROOT}\"")
      string(APPEND _cxxflags " --sysroot=\"${CMAKE_SYSROOT}\"")
    endif()
    if(APPLE)
      list(LENGTH CMAKE_OSX_ARCHITECTURES _arch_count)
      if(_arch_count GREATER 1)
        message(FATAL_ERROR "Build Garnet separately per Apple architecture; universal mruby is not yet supported")
      endif()
      if(CMAKE_OSX_ARCHITECTURES)
        string(APPEND _cflags " -arch ${CMAKE_OSX_ARCHITECTURES}")
        string(APPEND _cxxflags " -arch ${CMAKE_OSX_ARCHITECTURES}")
      endif()
      if(CMAKE_OSX_SYSROOT)
        string(APPEND _cflags " -isysroot \"${CMAKE_OSX_SYSROOT}\"")
        string(APPEND _cxxflags " -isysroot \"${CMAKE_OSX_SYSROOT}\"")
      endif()
      if(CMAKE_OSX_DEPLOYMENT_TARGET)
        string(APPEND _cflags " -mmacosx-version-min=${CMAKE_OSX_DEPLOYMENT_TARGET}")
        string(APPEND _cxxflags " -mmacosx-version-min=${CMAKE_OSX_DEPLOYMENT_TARGET}")
      endif()
    endif()
    set(_ld "${CMAKE_CXX_COMPILER}")
    set(_libname libmruby.a)
    set(_msvc false)
  endif()
  if(CMAKE_C_COMPILER_TARGET)
    string(APPEND _cflags " --target=${CMAKE_C_COMPILER_TARGET}")
  endif()
  if(CMAKE_CXX_COMPILER_TARGET)
    string(APPEND _cxxflags " --target=${CMAKE_CXX_COMPILER_TARGET}")
  endif()
  if(NOT MSVC)
    string(PREPEND _ldflags "${_cxxflags} ")
  endif()
  string(SHA256 _abi "${_garnet_revision}|${_recipe_hash}|${_driver_hash}|${CMAKE_C_COMPILER}|${CMAKE_CXX_COMPILER}|${CMAKE_C_COMPILER_VERSION}|${CMAKE_CXX_COMPILER_VERSION}|${CMAKE_SIZEOF_VOID_P}|${CMAKE_SYSTEM_NAME}|${CMAKE_SYSTEM_PROCESSOR}|${_config}|${_cflags}|${_cxxflags}|${_ld}|${_ldflags}|${CMAKE_AR}")
  set(_settings "{}")
  _garnet_json_set(_settings abi "${_abi}")
  _garnet_json_set(_settings cc "${CMAKE_C_COMPILER}")
  _garnet_json_set(_settings cxx "${CMAKE_CXX_COMPILER}")
  _garnet_json_set(_settings cflags "${_cflags}")
  _garnet_json_set(_settings cxxflags "${_cxxflags}")
  _garnet_json_set(_settings ld "${_ld}")
  _garnet_json_set(_settings ldflags "${_ldflags}")
  _garnet_json_set(_settings ar "${CMAKE_AR}")
  string(JSON _settings SET "${_settings}" msvc ${_msvc})
  string(JSON _settings SET "${_settings}" pointer_size ${CMAKE_SIZEOF_VOID_P})
  if(GARNET_MRUBY_BUILD_DIR)
    set(_output "${GARNET_MRUBY_BUILD_DIR}")
    if(NOT EXISTS "${_output}/garnet-build.json" OR NOT EXISTS "${_output}/include/mruby.h" OR
        NOT EXISTS "${_output}/lib/${_libname}")
      message(FATAL_ERROR "Prebuilt mruby must be a completed Garnet-managed build with garnet-build.json")
    endif()
    file(READ "${_output}/garnet-build.json" _manifest)
    string(JSON _built_abi GET "${_manifest}" abi)
    if(NOT _built_abi STREQUAL _abi)
      message(FATAL_ERROR "Prebuilt mruby configuration mismatch; rebuild from GARNET_MRUBY_SOURCE_DIR")
    endif()
    string(JSON _built_library_hash GET "${_manifest}" library_sha256)
    file(SHA256 "${_output}/lib/${_libname}" _library_hash)
    if(NOT _library_hash STREQUAL _built_library_hash)
      message(FATAL_ERROR "Prebuilt mruby archive differs from its completed build manifest")
    endif()
  else()
    set(_root "${CMAKE_CURRENT_BINARY_DIR}/mruby/${_config}")
    set(_output "${_root}/garnet")
    _garnet_json_set(_settings build_root "${_root}")
    file(GENERATE OUTPUT "${CMAKE_CURRENT_BINARY_DIR}/mruby-settings-${_config}.json" CONTENT "${_settings}\n")
    # minirake tracks MRUBY_CONFIG's timestamp. Change the wrapper when any
    # injected setting changes so existing object files cannot keep old flags.
    file(GENERATE OUTPUT "${CMAKE_CURRENT_BINARY_DIR}/mruby-config-${_config}.rb"
      CONTENT "# Configuration identity: ${_abi}\n# Source inputs: ${_inputs_hash}\nload ENV.fetch('GARNET_MRUBY_RECIPE')\n")
  endif()
  target_include_directories(garnet_mruby INTERFACE "$<$<CONFIG:${_config}>:${_output}/include>")
  target_link_libraries(garnet_mruby INTERFACE "$<$<CONFIG:${_config}>:${_output}/lib/${_libname}>")
endforeach()
if(NOT GARNET_MRUBY_BUILD_DIR)
  if(NOT EXISTS "${GARNET_MRUBY_SOURCE_DIR}/minirake")
    message(FATAL_ERROR "Supply GARNET_MRUBY_SOURCE_DIR pointing to the pinned local mruby checkout")
  endif()
  find_program(GARNET_RUBY_EXECUTABLE NAMES ruby REQUIRED)
  # mruby tracks its own source dependencies. One worker avoids hidden nested
  # parallelism exceeding the parent build's worker budget.
  add_custom_target(garnet_mruby_build
    COMMAND "${CMAKE_COMMAND}" -E rm -f
      "${CMAKE_CURRENT_BINARY_DIR}/mruby/$<CONFIG>/garnet/garnet-build.json"
    COMMAND "${CMAKE_COMMAND}" -E env
      "MRUBY_CONFIG=${CMAKE_CURRENT_BINARY_DIR}/mruby-config-$<CONFIG>.rb"
      "GARNET_MRUBY_RECIPE=${CMAKE_CURRENT_LIST_DIR}/mruby_build_config.rb"
      "GARNET_MRUBY_SETTINGS=${CMAKE_CURRENT_BINARY_DIR}/mruby-settings-$<CONFIG>.json"
      "${GARNET_RUBY_EXECUTABLE}" "${GARNET_MRUBY_SOURCE_DIR}/minirake" -j1
    COMMAND "${CMAKE_COMMAND}"
      "-DSETTINGS=${CMAKE_CURRENT_BINARY_DIR}/mruby-settings-$<CONFIG>.json"
      "-DARCHIVE=${CMAKE_CURRENT_BINARY_DIR}/mruby/$<CONFIG>/garnet/lib/${_libname}"
      "-DMANIFEST=${CMAKE_CURRENT_BINARY_DIR}/mruby/$<CONFIG>/garnet/garnet-build.json"
      -P "${CMAKE_CURRENT_LIST_DIR}/SealMruby.cmake"
    WORKING_DIRECTORY "${GARNET_MRUBY_SOURCE_DIR}"
    BYPRODUCTS "${CMAKE_CURRENT_BINARY_DIR}/mruby/$<CONFIG>/garnet/lib/${_libname}"
    VERBATIM)
  add_dependencies(garnet_mruby garnet_mruby_build)
endif()
